services:
  db:
    image: postgres
    container_name: a7m-db
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=a7m_db
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: a7m-redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./data/redis_data:/data
    command: redis-server --appendonly yes

  mailhog:
    image: mailhog/mailhog
    container_name: a7m-mailhog
    ports:
      - 1025:1025 # SMTP server port
      - 8025:8025 # Web UI port

networks:
  default:
    name: a7m-network
    driver: bridge
